### ISSUE TITLE
Model performance changing a lot.

### ISSUE THREAD

**Issue by himanshupant24** [wilsonrljr/sysidentpy#111]
I tried the model for an example with Y_lag=26 and x_lag=10. I ran the model 2-3 times. I am using NSE and RMSE as performance measurement. I found my NSE changing from 0.45 to -0.3. My question is , is the performance of the model expected to change this much with same data and configuration?

**Comment by ericglem** [comment]
I think the best way to assure the variability is large is by running a significant benchmark (i.e, more than 2-3 times) and taking some measurements (like mean, std, median, whatever). Have you tried that?

**Comment by wilsonrljr** [comment]
I agree with @ericglem. Besides, as I sent you by mail, if you could share a small sample of your data and code you are using it'd be great. Without some details its difficult to check whats is happening. 

For example: since you are using a neural network with stochastic optimizer, the performance can change each time you run it. But if the performance is changing too much we have to look at the data to check if it is a data related problem or is something else behind the scenes in the package implementation. 

Moreover, you said in the issue #110 you are having some troubles to defined the lags for multiple input cases, so maybe the problem can be related to some mistake in that part too.

But as I said, I have to look your code and data (just a sample) to have a proper answer.

**Comment by wilsonrljr** [comment]
Hey @himanshupant24 , I'll make some tests with the sample data you sent me.

Regarding the model performance changing, it can absolutely happen in your case (given the details you sent me by mail). In your case, you are changing the lags and, respectively, the model form, so the performance can vary a lot depending on the data.

I'll keep you updated.

**Comment by himanshupant24** [comment]
Hi @wilsonrljr,

Sorry to bother you again. Did you get a chance to have a look on the dataset?

Thanks,
Himanshu

**Comment by wilsonrljr** [comment]
First, I'm sorry if I didn't answer everything you need (I dont remember if we have discussed this also in discord or mail). I'm closing this for because you might have found a solution at this point). However, if you still need any help, please contact me. Because more people started using the package, now I have a specif schedule in my agenda every week  just to assist people with questions about the package.

Again, sorry if your question was "ghosted".
