### ISSUE TITLE
r2_score

### ISSUE THREAD

**Issue by AntoineDubois** [wilsonrljr/sysidentpy#91]
Hello,
The metric r2_score is buggy for multidimensional input.
One can quickly fix it by:
`sysidentpy.metrics.r2_score(Y_valid.flatten(), yhat.flatten())`
I am sure modifying the underlying code would ease its use
Thanks!

**Comment by wilsonrljr** [comment]
Hey, @AntoineDubois ! Thanks for open this issue. I was informed by another user about it and its already fix in the branch v0.2.2. I forgot to open an issue about it to get everyone warned.

The new version is already finished (I'm updating the docs because there is some breaking changes.. nothing critical, but I think it'll make the package usage easier to understand for beginners).

I'll try to release the new version til 11/02.

**Comment by AntoineDubois** [comment]
Thanks!

**Comment by wilsonrljr** [comment]
fixed in v0.3.0
